# Generated by Django 4.0.3 on 2022-03-29 13:39

import core.models
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='twitter',
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='imagem',
            field=stdimage.models.StdImageField(upload_to=core.models.get_file_path, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='instagram',
            field=models.CharField(default='#', max_length=100, verbose_name='twitter'),
        ),
    ]
