# Generated by Django 4.0.3 on 2022-03-30 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_funcionario_twitter_alter_funcionario_imagem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificados', models.DateField(auto_now=True, verbose_name='Atualizado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('feature', models.CharField(max_length=100, verbose_name='Serviço')),
                ('descricao', models.TextField(max_length=200, verbose_name='Descriçao')),
                ('icone', models.CharField(choices=[('lni-rocket', 'turbine'), ('lni-laptop-phone', 'repositorio'), ('lni-cog', 'engrenagem'), ('lni-leaf', 'design'), ('lni-layers', 'camada'), ('lni-leaf', 'formulario')], max_length=16, verbose_name='Icone')),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
            },
        ),
    ]
