# Generated by Django 4.0.3 on 2022-03-30 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='feature',
            field=models.CharField(max_length=100, verbose_name='Feature'),
        ),
    ]
